import { useEffect, useState } from 'react'
import './SettingsWorkspace.css'

type Settings = { validityDays: string; terms: string; taxProfiles: string[]; sections: string[] }
const key = 'vrs-smartquote.settings.v1'
const initial: Settings = { validityDays: '', terms: '', taxProfiles: [], sections: [] }
function load(): Settings { try { return { ...initial, ...(JSON.parse(localStorage.getItem(key) ?? '{}') as Partial<Settings>) } } catch { return initial } }

export function SettingsWorkspace({ tamil }: { tamil: boolean }) {
  const [settings, setSettings] = useState<Settings>(load)
  const [tax, setTax] = useState('')
  const [section, setSection] = useState('')
  useEffect(() => { localStorage.setItem(key, JSON.stringify(settings)) }, [settings])
  const text = tamil ? { eyebrow: 'கட்டமைப்பு', title: 'மேற்கோள் அமைப்புகள்', intro: 'இங்கே சேமிக்கப்படும் அமைப்புகள் எதிர்கால மேற்கோள்களுக்கான இயல்புநிலைகளாக பயன்படும். தேவையானபோது ஒவ்வொரு மேற்கோளிலும் அவற்றை மாற்றலாம்.', validity: 'இயல்புநிலை செல்லுபடியாகும் நாட்கள்', terms: 'இயல்புநிலை விதிமுறைகள்', tax: 'GST / வரி சுயவிவரங்கள்', taxHint: 'எ.கா. GST 18%', add: 'சேர்க்கவும்', sections: 'ஆவணப் பிரிவுகள்', sectionHint: 'எ.கா. பணியின் எல்லை', saved: 'தானாகச் சேமிக்கப்பட்டது', emptyTax: 'வரி சுயவிவரங்கள் இல்லை. GST மேற்கோளில் விருப்பமானதாக இருக்கும்.', emptySections: 'பிரிவுகள் இல்லை. உங்கள் தேவைக்கேற்ப பிரிவுகளைச் சேர்க்கவும்.' } : { eyebrow: 'Configuration', title: 'Quotation settings', intro: 'Settings saved here become defaults for future quotes. They can be changed for an individual quotation when needed.', validity: 'Default validity (days)', terms: 'Default terms and notes', tax: 'GST / tax profiles', taxHint: 'e.g. GST 18%', add: 'Add', sections: 'Document sections', sectionHint: 'e.g. Scope of work', saved: 'Saved automatically', emptyTax: 'No tax profiles. GST remains optional on quotations.', emptySections: 'No sections. Add the sections your business needs.' }
  function addTax() { if (tax.trim()) { setSettings((value) => ({ ...value, taxProfiles: [...value.taxProfiles, tax.trim()] })); setTax('') } }
  function addSection() { if (section.trim()) { setSettings((value) => ({ ...value, sections: [...value.sections, section.trim()] })); setSection('') } }
  return <div className="settings-workspace"><section className="settings-header"><div><p className="eyebrow">{text.eyebrow}</p><h1>{text.title}</h1><p>{text.intro}</p></div><span className="saved-status">✓ {text.saved}</span></section><div className="settings-grid"><section className="settings-card"><label>{text.validity}<input type="number" min="0" value={settings.validityDays} onChange={(event) => setSettings((value) => ({ ...value, validityDays: event.target.value }))} /></label><label>{text.terms}<textarea value={settings.terms} onChange={(event) => setSettings((value) => ({ ...value, terms: event.target.value }))} /></label></section><section className="settings-card"><h2>{text.tax}</h2><div className="settings-add"><input placeholder={text.taxHint} value={tax} onChange={(event) => setTax(event.target.value)} /><button type="button" className="secondary-add" onClick={addTax}>{text.add}</button></div>{settings.taxProfiles.length === 0 ? <p className="setting-empty">{text.emptyTax}</p> : <div className="chip-list">{settings.taxProfiles.map((item, index) => <span className="setting-chip" key={`${item}-${index}`}>{item}<button type="button" onClick={() => setSettings((value) => ({ ...value, taxProfiles: value.taxProfiles.filter((_, current) => current !== index) }))} aria-label="Remove">×</button></span>)}</div>}</section><section className="settings-card"><h2>{text.sections}</h2><div className="settings-add"><input placeholder={text.sectionHint} value={section} onChange={(event) => setSection(event.target.value)} /><button type="button" className="secondary-add" onClick={addSection}>{text.add}</button></div>{settings.sections.length === 0 ? <p className="setting-empty">{text.emptySections}</p> : <ol className="section-list">{settings.sections.map((item, index) => <li key={`${item}-${index}`}>{item}<button type="button" onClick={() => setSettings((value) => ({ ...value, sections: value.sections.filter((_, current) => current !== index) }))} aria-label="Remove">×</button></li>)}</ol>}</section></div></div>
}
